#################################
########### LOGIN ###############

#login to the application to get the token
POST http://{{hostname}}:{{port}}/api/login
Content-Type: application/json

{
    "username": "{{$dotenv HTTP_USERNAME}}",
    "password": "{{$dotenv HTTP_PASS}}"
}

####################################
########### METADATA ###############

### Get all possible makes of bikes
GET http://{{hostname}}:{{port}}/api/makes
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Get all possible models of a bike with given make
GET http://{{hostname}}:{{port}}/api/models?make=romet
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Get all possible models of a bike with given make
GET http://{{hostname}}:{{port}}/api/years?make=romet&model=aspre2
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

################################
########### FIND ###############

### Find by empty criteria - all user or public bikes data
GET http://{{hostname}}:{{port}}/api/bikes
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Find bikes by make
GET http://{{hostname}}:{{port}}/api/bikes?make=romet
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Find bikes by model
GET http://{{hostname}}:{{port}}/api/bikes?model=grv400
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Find bikes by year
GET http://{{hostname}}:{{port}}/api/bikes?year=2020
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Find bikes by text search
GET http://{{hostname}}:{{port}}/api/bikes?search=aaaa
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Find bikes matching all criteria
GET http://{{hostname}}:{{port}}/api/bikes?year=2022&model=aspre2&make=romet&search=Romet%20aspre2
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

#################################
########### FETCH ###############

### Get particular bike data
GET http://{{hostname}}:{{port}}/api/bike?id=6636c830d60e5d55445f874f
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Get particular bike image
GET http://{{hostname}}:{{port}}/api/bikeImage?id=6636c830d60e5d55445f874f
Authorization: Bearer {{$dotenv HTTP_TOKEN}}

### Get particular bike data and image
GET http://{{hostname}}:{{port}}/api/bikeFull?id=6636c830d60e5d55445f874f
Authorization: Bearer {{$dotenv HTTP_TOKEN}}